### ISSUE TITLE
Input Rate not corret

### ISSUE THREAD

**Issue by stich86** [NWMichl/NXOS_SNMP_Grafana#1]
Hi,

i've found your dashboard searching for a tool to monitor my Nexus switched.
Currently i'm trying to monitor (using Telegraf and SNMP v2) a Nexus 3K with NX-OS 6. The problem is that the statistics from  a network interface doesn't match the real one that can be retrived using "show interface Ethernet 1/43".

In my case the current interface speed is this one:

```
  Load-Interval #1: 30 seconds
  30 seconds input rate 3934339272 bits/sec, 323138 packets/sec
  30 seconds output rate 8526384 bits/sec, 13779 packets/sec
  Load-Interval #2: 5 minute (300 seconds)
    input rate 4.03 Gbps, 330.67 Kpps; output rate 8.69 Mbps, 14.00 Kpps
  RX
    792039442740 unicast packets  3492176 multicast packets  836749 broadcast packets
    792043771665 input packets  1155210089052281 bytes
    409193515996 jumbo packets  0 storm suppression packets

```

While on the dashboard si report four time bigger:

![image](https://user-images.githubusercontent.com/27808541/101161414-f44dc680-3630-11eb-8ee7-9b945c312684.png)

How can I fix this behaviour?

Thanks!

**Comment by NWMichl** [comment]
Looks good for me. I think you should compare the 30sec or 5min CLI load with the **avg** of the graph panel, not the max ;-)
Telegraf uses the standard if-MIB, so there is little chance to mess it up.

Regards,
Michael
